version: '2.4'

services:
    postgres:
        image: 'postgres:13.1'
        environment:
            - POSTGRES_PASSWORD=myPostgresPassword
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U postgres" ]
            interval: 10s
            timeout: 5s
            retries: 5
#    migrate:
#        build:
#            dockerfile: Dockerfile.development
#            context: .
#        entrypoint: npm run db:migrate
#        environment:
#            - NODE_ENV=development
#            - PG_HOST=postgres
#            - PG_PORT=5432
#            - PG_DATABASE=postgres
#            - PG_USER=postgres
#            - PG_PASSWORD=myPostgresPassword
#        volumes:
#            - .:/usr/src/app
#        depends_on:
#            postgres:
#                condition: service_healthy
    node:
        depends_on:
            -   postgres
        build:
            dockerfile: Dockerfile.development
            context: .
        entrypoint: /bin/sh -c "./entrypoint.sh"
#        command: ./node_modules/.bin/sequelize db:migrate
        volumes:
            - .:/usr/src/app
#            - /usr/src/app/node_modules
        environment:
            - NODE_ENV=development
            - PG_HOST=postgres
            - PG_PORT=5432
            - PG_DATABASE=postgres
            - PG_USER=postgres
            - PG_PASSWORD=myPostgresPassword
        ports:
            - '5000:5000'
            - '9229:9229'
